[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
build = "build.rs"
name = "utp"
version = "0.1.0"

[build-dependencies]
bindgen = "~0.42.1"

[dependencies]
libc = "0.2"
nix = "0.11"

[dev-dependencies]
net-literals = "0.1.2"
unwrap = "1.2.1"
